export type Network = {
  value: string;
  label: string;
  chainId: number;
  gnosisPrefix: string;
  logo: string;
  testnet?: boolean;
  transactionService?: string;
};

export const NETWORKS: Network[] = [
    // {
    //   value: "ethereum",
    //   label: "Ethereum",
    //   chainId: 1,
    //   gnosisPrefix: "eth",
    //   logo: "networks/ethereum.ico",
    // },
    // {
    //   value: "arbitrum",
    //   label: "Arbitrum",
    //   chainId: 42161,
    //   gnosisPrefix: "arb1",
    //   logo: "networks/arbitrum.ico",
    // },
    // {
    //   value: "optimism",
    //   label: "OP Mainnet",
    //   chainId: 10,
    //   gnosisPrefix: "oeth",
    //   logo: "networks/optimism.ico",
    // },
    // {
    //   value: "base",
    //   label: "Base",
    //   chainId: 8453,
    //   gnosisPrefix: "base",
    //   logo: "networks/base.ico",
    // },
    // {
    //   value: "worldchain",
    //   label: "Worldchain",
    //   chainId: 10252,
    //   gnosisPrefix: "wc",
    //   logo: "networks/worldchain.ico",
    // },
    // {
    //   value: "mantle",
    //   label: "Mantle",
    //   chainId: 5000,
    //   gnosisPrefix: "mnt",
    //   logo: "networks/mantle.ico",
    // },
    // {
    //   value: "polygon",
    //   label: "Polygon",
    //   chainId: 137,
    //   gnosisPrefix: "matic",
    //   logo: "networks/polygon.ico",
    // },
    // {
    //   value: "bsc",
    //   label: "BSC",
    //   chainId: 56,
    //   gnosisPrefix: "bnb",
    //   logo: "networks/bsc.ico",
    // },
    // {
    //   value: "avalanche",
    //   label: "Avalanche",
    //   chainId: 43114,
    //   gnosisPrefix: "avax",
    //   logo: "networks/avalanche.ico",
    // },
    // {
    //   value: "celo",
    //   label: "Celo",
    //   chainId: 42220,
    //   gnosisPrefix: "celo",
    //   logo: "networks/celo.ico",
    // },
    // {
    //   value: "gnosis",
    //   label: "Gnosis Chain",
    //   chainId: 100,
    //   gnosisPrefix: "gno",
    //   logo: "networks/gnosis.ico",
    // },
    // {
    //   value: "linea",
    //   label: "Linea",
    //   chainId: 59144,
    //   gnosisPrefix: "linea",
    //   logo: "networks/linea.ico",
    // },
    // {
    //   value: "zksync",
    //   label: "zkSync",
    //   chainId: 324,
    //   gnosisPrefix: "zksync",
    //   logo: "networks/zksync.ico",
    // },
    // {
    //   value: "polygon-zkevm",
    //   label: "Polygon zkEVM",
    //   chainId: 1101,
    //   gnosisPrefix: "zkevm",
    //   logo: "networks/polygon.ico",
    // },
    // {
    //   value: "scroll",
    //   label: "Scroll",
    //   chainId: 534352,
    //   gnosisPrefix: "scr",
    //   logo: "networks/scroll.ico",
    // },
    // {
    //   value: "xlayer",
    //   label: "xLayer",
    //   chainId: 204,
    //   gnosisPrefix: "xlayer",
    //   logo: "networks/xlayer.ico",
    // },
    // {
    //   value: "aurora",
    //   label: "Aurora",
    //   chainId: 1313161554,
    //   gnosisPrefix: "aurora",
    //   logo: "networks/aurora.ico",
    // },
    // {
    //   value: "blast",
    //   label: "Blast",
    //   chainId: 81457,
    //   gnosisPrefix: "blast",
    //   logo: "networks/blast.ico",
    // },
    // {
    //   value: "sepolia",
    //   label: "Sepolia",
    //   chainId: 11155111,
    //   gnosisPrefix: "sep",
    //   logo: "networks/ethereum.ico",
    // },
    // {
    //   value: "base-sepolia",
    //   label: "Base Sepolia",
    //   chainId: 84532,
    //   gnosisPrefix: "basesep",
    //   logo: "networks/base.ico",
    // },
    // {
    //   value: "gnosis-chiado",
    //   label: "Gnosis Chiado",
    //   chainId: 10200,
    //   gnosisPrefix: "chiado",
    //   logo: "networks/gnosis.ico",
    // },
    {
      value: "swell",
      label: "Swell",
      chainId: 1923,
      gnosisPrefix: "swell-l2",
      logo: "networks/swell.ico",
    },
    {
      value: "swell-testnet",
      label: "Swell Testnet",
      chainId: 1924,
      gnosisPrefix: "swell-l2-testnet",
      logo: "networks/swell-testnet.ico",
      testnet: true,
    },
    {
      value: "zircuit-mainnet",
      label: "Zircuit Mainnet",
      chainId: 48900,
      gnosisPrefix: "zircuit-mainnet",
      logo: "networks/zircuit.ico",
    },
    {
      value: "zircuit-testnet",
      label: "Zircuit Testnet",
      chainId: 48899,
      gnosisPrefix: "zircuit-testnet",
      logo: "networks/zircuit.ico",
      testnet: true,
    },
    {
      value: "harmony",
      label: "Harmony",
      chainId: 1666600000,
      gnosisPrefix: "hmy",
      logo: "networks/harmony.ico",
    },
    {
      value: "harmony-testnet",
      label: "Harmony Testnet",
      chainId: 1666700000,
      gnosisPrefix: "hmyt",
      logo: "networks/harmony.ico",
      testnet: true,
    },
    {
      value: "moca-mainnet",
      label: "Moca Chain Mainnet",
      chainId: 2288,
      gnosisPrefix: "moca",
      logo: "networks/moca.ico",
    },
    {
      value: "moca-testnet",
      label: "Moca Chain Testnet",
      chainId: 222888,
      gnosisPrefix: "mocat",
      logo: "networks/moca.ico",
      testnet: true,
    },
    {
      value: "plasma",
      label: "Plasma",
      chainId: 9745,
      gnosisPrefix: "plasma",
      logo: "networks/plasma.ico",
    },
    {
      value: "plasma-testnet",
      label: "Plasma Testnet",
      chainId: 9746,
      gnosisPrefix: "plasma-testnet",
      logo: "networks/plasma.ico",
      testnet: true,
    },
    {
      value: "blast",
      label: "Blast",
      chainId: 81457,
      gnosisPrefix: "blastmainnet",
      logo: "networks/blast.ico",
    },
    {
      value: "blast-sepolia",
      label: "Blast Sepolia Testnet",
      chainId: 168587773,
      gnosisPrefix: "blastsepolia",
      logo: "networks/blast-sepolia.ico",
      testnet: true,
    },
    {
      value: "wemix",
      label: "WEMIX3.0",
      chainId: 1111,
      gnosisPrefix: "wemix",
      logo: "networks/wemix.ico",
    },
    {
      value: "wemix-testnet",
      label: "WEMIX3.0 Testnet",
      chainId: 1112,
      gnosisPrefix: "twemix",
      logo: "networks/wemix.ico",
      testnet: true,
    },
    {
      value: "mantrachain",
      label: "MantraChain",
      chainId: 5888,
      gnosisPrefix: "mantrachain",
      logo: "networks/mantra.ico",
    },
    {
      value: "mantrachain-dukong",
      label: "MantraChain Dukong",
      chainId: 5887,
      gnosisPrefix: "dukong",
      logo: "networks/mantra-dukong.ico",
      testnet: true,
    },
    {
      value: "alpen",
      label: "Alpen Testnet II",
      chainId: 8150,
      gnosisPrefix: "alpen",
      logo: "networks/alpen.ico",
      testnet: true,
    },
    {
      value: "ault-testnet",
      label: "Ault Testnet",
      chainId: 10904,
      gnosisPrefix: "ault-testnet",
      logo: "networks/ault.ico",
      testnet: true,
    },
    {
      value: "dogeos-chykyu",
      label: "DogeOS Chikyū Testnet",
      chainId: 6281971,
      gnosisPrefix: "dogeos-chykyu",
      logo: "networks/dogeos.ico",
      testnet: true,
    },
    {
      value: "hoodi-testnet",
      label: "Hoodi Testnet",
      chainId: 560048,
      gnosisPrefix: "hoe",
      logo: "networks/hoodi.ico",
      testnet: true,
    },
    {
      value: "tempo-testnet",
      label: "Tempo Moderato Testnet",
      chainId: 42431,
      gnosisPrefix: "tempo-moderato",
      logo: "networks/tempo.ico",
      testnet: true,
    },
  ];